### ISSUE TITLE
Getting Resources not found

### ISSUE THREAD

**Issue by tirthankarhalder** [ConnectedSystemsLab/xwr_raw_ros#1]
Hello, I have installed [ti_mmwave_rospkg](https://github.com/radar-lab/ti_mmwave_rospkg) and [https://github.com/wjwwood/serial](Serial) inside a different workspace directory according to the instructions (Path as follows: **\mmRos\src\**). 
But whenever I am running **roslaunch xwr_raw_ros radar_pcd.launch**
It is giving the PATH error by throwing an exception:

Resource not found: ti_mmwave_rospkg
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/jetson/catkin_ws/src/xwr_raw_ros
ROS path [2]=/opt/ros/noetic/share
The traceback for the exception was written to the log file

using UBUNTU 20.04 4.9.253-tegra aarch64

**Comment by sie2** [comment]
you need to install [ti_mmwave_rospkg](https://github.com/radar-lab/ti_mmwave_rospkg) as well.
