### ISSUE TITLE
Ros 2 Port

### ISSUE THREAD

**Issue by TitouanTyack** [ConnectedSystemsLab/xwr_raw_ros#2]
Hi, 

Thank you for the amazing work done. 
I started a ros2 port of your code in a fork.
For know, I managed to use the C recver, configured by the python script (radar_cfg.py) and the ra visualizer (visra.py) works too.
I also managed to get simultaneously the point cloud using the DataHandlerClass node of the  [ros2 ti mmwave driver](https://git.ti.com/cgit/mmwave_radar/mmwave_ti_ros).

I only tried with the AWR1843 for now.

If you want, i can do a pull request to a ros2 branch.

Also, I have a question, did you managed to get pointcloud from an AWR2944 ? Thanks

Titouan

**Comment by sie2** [comment]
Thanks for letting us know you were able to get it to work. Feel free to send the pull request for the ros2 version.

As for the AWR2944, I have not tried to get point clouds from it. But I suspect the process should not be too different from the other boards.
